### ISSUE TITLE
Visualize Results?

### ISSUE THREAD

**Issue by lolz0r** [longjon/caffe#2]
Hi,
I was curious how one actually visualizes the output of the net in the same fashion that you do with your paper? 

Please let me know if you have any insight.

Thank you,
Michael

**Comment by charterscruz** [comment]
Hi @lolz0r,

This issue is kind of old but might be useful for others.
Not really sure of what you meant by visualize results but if you are referring to a way to show the result in eval.py when you get:
`out = net.blobs['score'].data[0].argmax(axis=0)`
then you might do:

```
plt.imshow(out)
plt.show()
```

**Comment by shelhamer** [comment]
@charterscruz is correct, and further if you want to palette the outputs to fit the PASCAL VOC color scheme you can transfer it from an existing PASCAL image.

Here is a hack for doing so:

```
import Image
import copy

def palette_gt(gt):
    voc_dir = 'PASCAL/VOC2011'
    reference_idx = '2008_000666'
    palette_im = Image.open('{}/SegmentationClass/{}.png'.format(voc_dir, reference_idx))
    gt_im = Image.fromarray(gt, mode='P')
    gt_im.palette = copy.copy(palette_im.palette)
    return gt_im
```
