### ISSUE TITLE
Failed to run eval.py of FCN-32S

### ISSUE THREAD

**Issue by ghost** [longjon/caffe#5]
I have just tried to run the `eval.py` using FCN-32s model. But I get the following error

```
F1105 19:29:04.896656 25800 layer_factory.hpp:77] Check failed: registry.count(type) == 1 (0 vs. 1) Unknown layer type: Crop (known types: AbsVal, Accuracy, ArgMax, BNLL, Concat, ContrastiveLoss, Convolution, Data, Deconvolution, Dropout, DummyData, Eltwise, EuclideanLoss, Exp, Flatten, HDF5Data, HDF5Output, HingeLoss, Im2col, ImageData, InfogainLoss, InnerProduct, LRN, MVN, MemoryData, MultinomialLogisticLoss, PReLU, Pooling, Power, Python, ReLU, Sigmoid, SigmoidCrossEntropyLoss, Silence, Slice, Softmax, SoftmaxWithLoss, Split, TanH, Threshold, WindowData)
*** Check failure stack trace: ***
Aborted (core dumped)
```

which says that the `Crop` is an unknown layer type. I have no idea of what is going wrong. Could anyone give me some suggestions?

BTW, I use the required `caffe-future` brach: I download and unzip `caffe-future.zip`. Then I copy the `Makefile.config` from `caffe-master` to it and successfully run `make all` and `make pycaffe`.

**Comment by creinders** [comment]
I had the same problem and I noticed that I imported the wrong caffe branch. Make sure that you import the correct one. You can print for example the caffe path:

```
print caffe.__path__
```

**Comment by ghost** [comment]
@creinders Thanks for your nice suggestions! :+1:

**Comment by ayumiymk** [comment]
but I use this python code, can't get author's mean I/U, do you kown some errors?

**Comment by bubulv** [comment]
@ayumiymk I want to know how to produce the label-lmdb? which model do you ues? I used the FCN-32s PASCAL-Context, but don't know how to ues the pascal-context database

**Comment by shelhamer** [comment]
Closing since the `future` branch is now deprecated; the relevant functionality has been merged to master.

Check out the [fcn.berkeleyvision.org repo](https://github.com/shelhamer/fcn.berkeleyvision.org) for master editions of the reference networks, weights, and code for learning, inference, and scoring. For now just the PASCAL VOC nets have been ported, but PASCAL-Context will be included there too. The example of a Python data layer for FCNs may help clear up the data.

**Comment by ManyuChang** [comment]
@Jianchao-ICT  I have the question too. I want to know whether you have solved it? 
Thanks in advance!
